// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nethereum.Metamask.Blazor.Server.DAL;

namespace Nethereum.Metamask.Blazor.Server.Migrations
{
    [DbContext(typeof(VerContext))]
    [Migration("20200511165252_quick search")]
    partial class quicksearch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nethereum.Metamask.Blazor.Server.DB_Models.Diploma_model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComfirmationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdentityNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("RectorsLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RectorsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SB_nr")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudiesProgramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudiesProgrammeGovermentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Studiesdirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Diploma");
                });

            modelBuilder.Entity("Nethereum.Metamask.Blazor.Server.DB_Models.PdfInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("diplomaID")
                        .HasColumnType("int");

                    b.Property<string>("pdfBase64Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quickSearch")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("diplomaID");

                    b.ToTable("pdfInfos");
                });

            modelBuilder.Entity("Nethereum.Metamask.Blazor.Server.DB_Models.PdfInfo", b =>
                {
                    b.HasOne("Nethereum.Metamask.Blazor.Server.DB_Models.Diploma_model", "diploma")
                        .WithMany()
                        .HasForeignKey("diplomaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
